server: 
  port: 9999
  contextPath: /ui
#  session: 
#    cookie: 
#      name: UISESSION
  
security: 
  basic: 
    enabled: false
  oauth2: 
    client: 
      clientId: trusted-app
      clientSecret: secret
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
    resource: 
      userInfoUri: http://localhost:8080/user